@startuml

skinparam BackgroundColor #FFF68F

state "未完成" as 1
state "已接受" as 2
state "已取消" as 3
state "已备餐" as 4
state "待送餐" as 5
state "已送餐" as 6


1 --> 2:系统接受\n订单
1 --> 3:顾客取消\n未支付
2 --> 3:顾客取消\n未支付
2 --> 4:自助餐厅\n准备食物
4 --> 5:食堂工作人员\n请求送餐
4 --> 3:顾客取消\n已支付
5 --> 6:送餐人员送餐
5 --> 2:顾客拒收
6 --> [*]
3 --> [*]

@enduml